### ISSUE TITLE
How to extend complex_bessel to long double

### ISSUE THREAD

**Issue by ChiaCheng-Tsai** [valandil/complex_bessel#22]
As title

**Comment by joeydumont** [comment]
The underlying Fortran library only supports double precision, not long double. The only way would be to rewrite the Fortran routines to support long double. 

If you need more precision, I would recommend looking at the arbitrary precision libraries linked in the README of the project.

**Comment by ChiaCheng-Tsai** [comment]
FYI. Currently, arblib (https://arblib.org/) has no bessel functions for floating-point numbers but only for arbitrary precision number (without exponent). And boost::bessel only accepts real arguments. Therefore, your lib is still the best one for C++.
