### ISSUE TITLE
Help for writing correct attribution in project

### ISSUE THREAD

**Issue by ChristianBelloni** [valandil/complex_bessel#23]
Hi, i'm currently working on a similar project in rust and i used a lot of your code in it,
Do you mind telling me how do you wish to be cited ?
I'm sorry but i'm fairly new and i don't want to make mistakes before publishing on crates.io

here's the repo: https://github.com/ChristianBelloni/complex-bessel-rs

Have a nice day!

**Comment by joeydumont** [comment]
Hi Christian! 

The link you have on the README is perfectly fine. I'd encourage you to add a license (I believe our single file would need to GPLv3, but your own code could be whatever). 

If you're thinking academic citation that would do, but I don't really have a problem if you don't use that either. 
```bibtex
@software{joey_dumont_2015_18220,
  author       = {Joey Dumont and
                  Denis Gagnon},
  title        = {complex\_bessel: Release 0.6},
  month        = jun,
  year         = 2015,
  publisher    = {Zenodo},
  version      = {release-0.6},
  doi          = {10.5281/zenodo.18220},
  url          = {https://doi.org/10.5281/zenodo.18220}
}
```

Thanks for using the code and sharing that with me! Let me know if you find bugs :)
