### ISSUE TITLE
[feature request] spherical hankel functions

### ISSUE THREAD

**Issue by thisch** [valandil/complex_bessel#6]
Can you please add convenience functions for spherical hankel/bessel functions?

Regards
Thomas

**Comment by valandil** [comment]
Hi, 

This is indeed a good idea. I'll try to add them in next few weeks. I will test the results first myself, but before using this in production code, it might be a good idea to run some tests yourself. 

Thanks!

**Comment by thisch** [comment]
Thanks for that!

**Comment by valandil** [comment]
A preliminary version of the spherical Bessel functions has been implemented. I have not extensively tested the values it outputs, however, as NumPy only implements positive, integer-order versions of the spherical Bessel functions. I checked a couple of values at real orders and complex arguments with Mathmetica, and it seems to output the same values. More extensive testing needed.

**Comment by thisch** [comment]
Great. Thank you very much. I will test it as well and will probably add more unit tests

**Comment by valandil** [comment]
For now, I have only implemented sph_besselJ, sph_besselY, sph_hankelH1 and sph_hankelH2, the naïve way, i.e. by computing sqrt(pi/(2*z))*besselJ. I plan on writing code to evaluate the derivatives of the spherical functions, as well as implementing sph_besselI and sph_besselK. It might be a while, thougoh, as I don't have much time to dedicate to this project. 

I would be extremely grateful if you could submit unit tests. Thanks!
