### ISSUE TITLE
Compile simpleTest.cpp errors

### ISSUE THREAD

**Issue by qaler** [valandil/complex_bessel#7]
Hi valandil, thank you very much for your work porting complex bessel functions to c++ library.
I've encountered a problem here, when I try to compile tests/simpleTest.cpp with command "g++ -lgfortran -lcomplex_bessel simpleTest.cpp " to check if the library installed successfully or not, I got this errors:
/tmp/ccGbRgNM.o: In function `sp_bessel::besselJ(double, std::complex<double>)':
simpleTest.cpp:(.text._ZN9sp_bessel7besselJEdSt7complexIdE[_ZN9sp_bessel7besselJEdSt7complexIdE]+0x101): undefined reference to `zbesj_wrap'
simpleTest.cpp:(.text._ZN9sp_bessel7besselJEdSt7complexIdE[_ZN9sp_bessel7besselJEdSt7complexIdE]+0x250): undefined reference to `zbesy_wrap'
/tmp/ccGbRgNM.o: In function `sp_bessel::besselY(double, std::complex<double>)':
simpleTest.cpp:(.text._ZN9sp_bessel7besselYEdSt7complexIdE[_ZN9sp_bessel7besselYEdSt7complexIdE]+0x116): undefined reference to `zbesy_wrap'
simpleTest.cpp:(.text._ZN9sp_bessel7besselYEdSt7complexIdE[_ZN9sp_bessel7besselYEdSt7complexIdE]+0x254): undefined reference to `zbesj_wrap'
/tmp/ccGbRgNM.o: In function `sp_bessel::besselK(double, std::complex<double>)':
simpleTest.cpp:(.text._ZN9sp_bessel7besselKEdSt7complexIdE[_ZN9sp_bessel7besselKEdSt7complexIdE]+0xcb): undefined reference to `zbesk_wrap'
collect2: error: ld returned 1 exit status

I don't know what's wrong with it. Hope you can have time to look into it.
FYI, my os is Ubuntu 15.04. Also I've commented the lines containing besselH1 and besselH1p.
Thank you again!
Regards!

**Comment by valandil** [comment]
Hi qaler, 

I cannot seem to replicate this issue. Try writing
```bash
 g++ simpleTest.cpp -lcomplex_bessel -lgfortran
```
instead. Sometimes the order matters. 

It's embarassing to have such a dumb mistake with `besselH1` and `besselH1p` still left in the tests. I'll correct this at once. Thanks!
